### ISSUE TITLE
Exit code 1 when run in Kubernetes

### ISSUE THREAD

**Issue by keithbo** [billmcilhargey/docker-gunbot#9]
I've been attempting to get docker-gunbot to run within a Kubernetes cluster but it goes in to CrashLoopFallback with an exit code of 1.
Is there a way to get additional debug output to trace the error? When run within docker on my localhost it works as expected.
This console image is the only output I have to go on
<img width="604" alt="image" src="https://github.com/computeronix/docker-gunbot/assets/11249482/12c85669-b9ce-4b26-a269-766b88ff7332">
When triggering startup.sh manually everything appears to start but the server just exits without any further log output.
Deployment yaml is as follows, it is pretty basic
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gunthy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gunthy
  template:
    metadata:
      name: gunthy
      labels:
        name: gunthy
    spec:
      volumes:
        - name: gunthy
          persistentVolumeClaim:
            claimName: gunthy-pvc
      nodeSelector:
        csi.driver/nfs: 'true'
      containers:
        - name: gunbot
          image: 'computeronix/gunbot:latest'
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          securityContext:
            capabilities:
              add: [ "SYS_TIME" ]
          volumeMounts:
            - name: gunthy
              mountPath: /mnt/gunbot
---
kind: Service
apiVersion: v1
metadata:
  name: gunthy-lb
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    name: gunthy
  type: LoadBalancer
  loadBalancerIP: 10.10.0.2
```
